version: "3.8"

services:
  react:
    build: react/.
    container_name: react
    environment:
      - REACT_APP_HOST_IP=${HOST_IP}
      - REACT_APP_REDIRECT_URI=${REDIRECT_URI}
      - REACT_APP_CLIENT_ID=${CLIENT_ID}
      - USER_GID=${USER_GID}
      - GENERATE_SOURCEMAP=${GENERATE_SOURCEMAP}
    ports:
      - "3000:3000"
    volumes:
      - ./debug/react:/debug/src
  django:
    build: django/.
    container_name: django
    depends_on:
      postgresql:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./debug/django:/debug/backend
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - HOST_IP=${HOST_IP}
      - USER_GID=${USER_GID}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
  postgresql:
    build: postgres/.
    container_name: postgresql
    environment:
      - PGDATA=${PGDATA}
      - LD_LIBRARY_PATH=${LD_LIBRARY_PATH}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: pg_isready -d django_db -U postgres -h postgresql -p 5432
      interval: 5s
      retries: 3
