const languages = {
  en: {
    register: 'Register',
    login: 'Login',
    email: 'Email',
    firstName: 'First Name',
    lastName: 'Last Name',
    username: 'Username',
    password: 'Password',
    registerButton: 'Register',
    loginButton: 'Login',
    logoutButton: 'Log out',
    language: 'Language',
    english: 'English',
    german: 'German',
    french: 'French',
    loggedInMessage: "You're logged in!",
    registerHeader: 'Register',
    loginHeader: 'Login',
    login42: 'Login 42',
    authenticationapp:' authentification app'
  },
  de: {
    register: 'Registrieren',
    login: 'Anmelden',
    email: 'E-Mail',
    firstName: 'Vorname',
    lastName: 'Nachname',
    username: 'Benutzername',
    password: 'Passwort',
    registerButton: 'Registrieren',
    loginButton: 'Anmelden',
    logoutButton: 'Abmelden',
    language: 'Sprache',
    english: 'Englisch',
    german: 'Deutsch',
    french: 'Französisch',
    loggedInMessage: 'Sie sind angemeldet!',
    registerHeader: 'Registrieren',
    loginHeader: 'Anmelden',
    login42: 'Anmelden 42',
    authenticationapp:'zabi'
  },
  fr: {
    register: "S'inscrire",
    login: 'Connexion',
    email: 'E-mail',
    firstName: 'Prénom',
    lastName: 'Nom de famille',
    username: "Nom d'utilisateur",
    password: 'Mot de passe',
    registerButton: "S'inscrire",
    loginButton: 'Connexion',
    logoutButton: 'Se déconnecter',
    language: 'Langue',
    english: 'Anglais',
    german: 'Allemand',
    french: 'Français',
    loggedInMessage: 'Vous êtes connecté(e)!',
    registerHeader: 'S\'inscrire',
    loginHeader: 'Connexion',
    login42: 'Connexion 42',
    authenticationapp:' application'
  }
};

export default languages;
